###
#
# DEPRECATED: This Action can be removed as soon as we start working on V2/V9
#
###

name: Deploy Demo App Preview to Netlify
on:
  workflow_run:
    workflows: ['Build Demo App']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-pnpm

      - name: Setup netlify-cli
        uses: ./.github/actions/setup-netlify-cli

      - name: Download build artifacts
        uses: ./.github/actions/artifact-download
        id: build
        with:
          name: design-system-demo
          folder: build-output

      - name: Deploy Documentation Preview
        id: deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # run command taken from https://gist.github.com/oneohthree/f528c7ae1e701ad990e6, shortened to 28 chars, prepended with build-number
        run: |
          url_alias=`echo "preview-${{ steps.build.outputs.id }}" | iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z`
          echo "preview-url=https://$url_alias--spds-test.netlify.app" >> $GITHUB_OUTPUT
          netlify deploy --filter @swisspost/design-system-demo --build false --dir ${{ steps.build.outputs.folder }} --alias $url_alias

      - name: Update preview message
        uses: ./.github/actions/preview/message/update
        with:
          access-token: ${{ secrets.SWISSPOSTDEVS_ACCESS_TOKEN }}
          issue-number: ${{ steps.build.outputs.id }}
          preview-url: ${{ steps.deploy.outputs.preview-url }}
