name: Release Major Version

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  data-gathering:
    name: Data Gathering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get versions.json
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.SWISSPOSTDEVS_ACCESS_TOKEN }}
          script: |
            const fs = require('fs')
            const path = require('path')
            const versions = JSON.parse(fs.readFileSync('./packages/documentation/public/assets/versions.json', 'utf8'))
            const lastVersion = versions[0].version
            console.log(lastVersion)
